#! /bin/bash
TOPXY="$1,$2" 
INRES="1920x1080"                                           # input resolution - this will only capture this area from you screen !  
OUTRES="720x480"                                           # Output resolution  - high:OUTRES="1280x720" 720p OUTRES="1920x1080" 1080p (FULL HD) !NOTE! USE THE HIGH OUTRES ONLY WITH A HIGH BANDWIDTH !!!
FPS="30"                                                   # target - FPS 30fps or 60fps are good. 15fps are the minimum ! 
QUAL="medium"                                                # - one of the many FFMPEG preset on ubuntu found in /usr/share/ffmpeg


# If you have low bandwidth, set the QUAL preset on 'fast' (upload bandwidth)
# If you have medium bandwitch, put it on medium (normal quality) 
 
# Write your key in a file named .twitch_key in your home directory
STREAM_KEY=$(cat ~/.twitch_key)  
# This is your streamkey generated by justintv/twitchtv found at: 
#justintv: http://www.justin.tv/broadcast/
#twitchtv: http://www.twitch.tv/broadcast/
#anther video codec you can use is this #avconv \ or #ffmpeg \
 
     ffmpeg \
    -f x11grab -s $INRES  -r "$FPS" -i :0.0+$TOPXY \
    -f alsa -ac 2 -i pulse  \
    -vcodec libx264 -s $OUTRES -preset $QUAL \
    -acodec libmp3lame -ar 44100 -threads 4 -qscale 3 -b 100000  -bufsize 512k \
    -f flv "rtmp://live.justin.tv/app/$STREAM_KEY"

#troubleshoot
#if you can't run this, becuase an encoder is missing try this in your terminal:
#sudo apt-get install ffmpeg libavcodec-extra-52
#if this doesn't work try this:
#sudo apt-get install ffmpeg libavcodec-extra-53  
